"""Del cat

Revision ID: 372fdaab7138
Revises: 22a06b9be06b
Create Date: 2021-08-14 11:22:32.203071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372fdaab7138'
down_revision = '22a06b9be06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
