"""table changes

Revision ID: 74d9157016d4
Revises: 3c4f233bd8f7
Create Date: 2021-08-13 08:14:01.776960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d9157016d4'
down_revision = '3c4f233bd8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
